#!/bin/bash
echo -e "int _putchar(char c){\n return (0);\n}" > _putchar.c
echo -e "int _islower(int c){\n return (0);\n}" > 3-islower.c
echo -e "int _isalpha(int c){\n return (0);\n}" > 4-isalpha.c
echo -e "int _abs(int n){\n return (0);\n}" > 6-abs.c
echo -e "int _isupper(int c){\n return (0);\n}" > 0-isupper.c
echo -e "int _isdigit(int c){\n return (0);\n}" > 1-isdigit.c
echo -e "int _strlen(char *s){\n return (0);\n}" > 2-strlen.c
echo -e "void _puts(char *s){\n return (0);\n}" > 3-puts.c
echo -e "char *_strcpy(char *dest, char *src){\n  return (0);\n}" > 9-strcpy.c
echo -e "int _atoi(char *s){\n return (0);\n}" > 100-atoi.c
echo -e "char *_strcat(char *dest, char *src){\n return (0){\n return(0);\n}" >0-strcat.c
echo -e "char *_strncat(char *dest, char *src, int n){\n return (0);\n}" > 1-strncat.c
echo -e "char *_strncpy(char *dest, char *src, int n){\n	return (0);\n}" > 2-strncpy.c
echo -e "int _strcmp(char *s1, char *s2){\n return (0);\n}" > 3-strcmp.c
echo -e "char *_memset(char *s, char b, unsigned int n){\n return (0);\n}" > 0-memset.c
echo -e "char *_memcpy(char *dest, char *src, unsigned int n){\n return (0);\n}" > 1-memcpy.c
echo -e "char *_strchr(char *s, char c){\n return (0);\n}" > 2-strchr.c
echo -e "unsigned int _strspn(char *s, char *accept){\n return (0);\n}" > 3-strspn.c
echo -e "char *_strpbrk(char *s, char *accept){\n return (0);\n}" > 4-strpbrk.c
echo -e "char *_strstr(char *haystack, char *needle){\n return (0);\n}" > 5-strstr.c
